### ISSUE TITLE
.attr('value') fails on input elements

### ISSUE THREAD

**Issue by filmaj** [xuijs/xui#29]
Confirmed in Chrome 10.0.648.205, Firefox 4, BlackBerry Browser 6 and 5.

**Comment by bryfox** [comment]
I assume this comes down to the difference between input.getAttribute('value') and input.value. I've used a val() extension in the past: https://gist.github.com/948971 rather than patching attr(). I don't know if there's a real use case for wanting to get at the former, but anyway. Maybe this gist saves you a few minutes.

**Comment by filmaj** [comment]
Totally true - thanks for the gist!
